/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CustomImport } from './routes/custom'
import { Route as FileImport } from './routes/$file'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CustomRoute = CustomImport.update({
  path: '/custom',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/custom.lazy').then((d) => d.Route))

const FileRoute = FileImport.update({
  path: '/$file',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$file.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$file': {
      id: '/$file'
      path: '/$file'
      fullPath: '/$file'
      preLoaderRoute: typeof FileImport
      parentRoute: typeof rootRoute
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$file': typeof FileRoute
  '/custom': typeof CustomRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$file': typeof FileRoute
  '/custom': typeof CustomRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$file': typeof FileRoute
  '/custom': typeof CustomRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$file' | '/custom'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$file' | '/custom'
  id: '__root__' | '/' | '/$file' | '/custom'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FileRoute: typeof FileRoute
  CustomRoute: typeof CustomRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FileRoute: FileRoute,
  CustomRoute: CustomRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$file",
        "/custom"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$file": {
      "filePath": "$file.tsx"
    },
    "/custom": {
      "filePath": "custom.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
